baseurl = "/"
title = "Chinh's Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Hi I'm Chinh"
    description = "My journey to learn to code in 10 years and maybe more."
    github = "https://github.com/hiimchinh"
    twitter = "https://twitter.com/hiimchinh"
    linkedin = "https://linkedin.com/in/hiimchinh"
    email = "chinh@hiimchinh.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:filename/"
    page = "/:filename/"
