baseurl = "/"
title = "Hi I'm Chinh"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Chinh Hoang | A Software Engineer"
    description = "Hi, I'm Chinh. I like to build and share stuff to learn."
    github = "https://github.com/hiimchinh"
    twitter = "https://twitter.com/hiimchinh"
    email = "me@hiimchinh.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
