baseurl = "/"
title = "Chinh's Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Chinh's Blog"
    description = "Change this"
    github = "https://github.com/hiimchinh"
    twitter = "https://twitter.com/hiimchinh"
    email = "chinh@hiimchinh.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
    page = "/:filename/"
